const RosterWwe2k24 = [
    {
        dlc: 'Pat Mcafee Pack',
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/ajHawk.webp',
        name: 'Aj Hawk',
        media: '78',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/ajStyles.webp',
        name: 'Aj Styles',
        media: '85',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/akiraTozawa.webp',
        name: 'Akira Tozawa',
        media: '68',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Female',
        image: './Images/RosterWwe2k24/albaFyre.webp',
        name: 'Alba Fyre',
        media: '74',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Female',
        image: './Images/RosterWwe2k24/alexaBliss.webp',
        name: 'Alexa Bliss',
        media: '83',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/andreChase.webp',
        name: 'Andre Chase',
        media: '73',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/andreTheGiant.webp',
        name: '	Andre The Giant',
        media: '91',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/angelGarza.webp',
        name: 'Angel Garza',
        media: '67',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/angeloDawkins.webp',
        name: 'Angelo Dawkins',
        media: '74',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/apolloCrews.webp',
        name: 'Apollo Crews',
        media: '71',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Male',
        image: './Images/RosterWwe2k24/ashanteTheeAdonis.webp',
        name: 'Ashante Thee Adonis',
        media: '62',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Female',
        image: './Images/RosterWwe2k24/asuka.webp',
        name: 'Asuka',
        media: '90',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        category: 'Striker',
        gender: 'Female',
        image: './Images/RosterWwe2k24/asuka64Bit.webp',
        name: 'Asuka (64 Bit)',
        media: '86',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/austinTheory.webp',
        name: 'Austin Theory',
        media: '72',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'High Flyer',
        gender: 'Male',
        image: './Images/RosterWwe2k24/axiom.webp',
        name: 'Axiom',
        media: '73',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Male',
        image: './Images/RosterWwe2k24/badBunny.webp',
        name: 'Bad Bunny',
        media: '78',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Male',
        image: './Images/RosterWwe2k24/baronCorbin.webp',
        name: 'Baron Corbin',
        media: '76',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/batista.webp',
        name: 'Batista',
        media: '89',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/batista08.webp',
        name: 'Batista 2008',
        media: '91',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Female',
        image: './Images/RosterWwe2k24/bayley.webp',
        name: 'Bayley',
        media: '85',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Female',
        image: './Images/RosterWwe2k24/beckyLynch.webp',
        name: 'Becky Lynch',
        media: '94',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Female',
        image: './Images/RosterWwe2k24/beckyLynch19.webp',
        name: 'Becky Lynch 2019',
        media: '90',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        category: 'Technician',
        gender: 'Female',
        image: './Images/RosterWwe2k24/beckyLynch18.webp',
        name: 'Becky Lynch 2018',
        media: '87',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Female',
        image: './Images/RosterWwe2k24/bethPhoenix.webp',
        name: 'Beth Phoenix',
        media: '87',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Female',
        image: './Images/RosterWwe2k24/biancaBelair.webp',
        name: 'Bianca Belair',
        media: '95',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        category: null,
        gender: 'Female',
        image: './Images/RosterWwe2k24/biancaBelair64Bit.webp',
        name: 'Bianca Belair (64 Bit)',
        media: '87',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Deluxe Edition',
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Female',
        image: './Images/RosterWwe2k24/biancaBelair17.webp',
        name: 'Bianca Belair 2017',
        media: '70',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/bigBossMan.webp',
        name: 'Big Boss Man',
        media: '79',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/bigE.webp',
        name: 'Big E',
        media: '78',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/bigPoppaPumpScottSteiner.webp',
        name: '"Big Poppa Pump" Scott Steiner',
        media: '83',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Female',
        image: './Images/RosterWwe2k24/blairDavenport.webp',
        name: 'Blair Davenport',
        media: '74',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/bobbyLashley.webp',
        name: 'Bobby Lashley',
        media: '89',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/boogeyman.webp',
        name: 'Boogeyman',
        media: '74',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Male',
        image: './Images/RosterWwe2k24/bookerT.webp',
        name: 'Booker T',
        media: '85',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        category: 'Striker',
        gender: 'Male',
        image: './Images/RosterWwe2k24/bookerT01.webp',
        name: 'Booker T 2001',
        media: '85',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Pat Mcafee Pack',
        cardPerson: false,
        category: 'High Flyer',
        gender: 'Male',
        image: './Images/RosterWwe2k24/bostonConnor.webp',
        name: 'Boston Connor',
        media: '71',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/braunStrowman.webp',
        name: 'Braun Strowman',
        media: '82',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/brayWyatt.webp',
        name: 'Bray Wyatt',
        media: '90',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Bray Wyatt Edition',
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/brayWyattElite.webp',
        name: 'Bray Wyatt "Élite"',
        media: '90',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/brayWyatt20.webp',
        name: 'Bray Wyatt 2020',
        media: '88',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/brayWyatt20nwo.webp',
        name: 'Bray Wyatt 2020 (nWo)',
        media: '87',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/brayWyatt20snme.webp',
        name: 'Bray Wyatt 2020 (SNME)',
        media: '85',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/bretHart.webp',
        name: 'Bret Hart',
        media: '93',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/bretHart92.webp',
        name: 'Bret Hart 1992',
        media: '83',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/britishBulldog.webp',
        name: 'British Bulldog',
        media: '85',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/bronBreakker.webp',
        name: 'Bron Breakker',
        media: '80',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/bronsonReed.webp',
        name: 'Bronson Reed',
        media: '84',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Male',
        image: './Images/RosterWwe2k24/brooksJensen.webp',
        name: 'Brooks Jensen',
        media: '67',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/brunoSammartino.webp',
        name: 'Bruno Sammartino',
        media: '91',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/brutusCreed.webp',
        name: 'Brutus Creed',
        media: '78',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'ECW Punk Pack',
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/bubbaRayDudley.webp',
        name: 'Bubba Ray Dudley',
        media: '85',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/butch.webp',
        name: 'Butch',
        media: '75',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/cactusJack.webp',
        name: 'Cactus Jack',
        media: '82',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Male',
        image: './Images/RosterWwe2k24/cameronGrimes.webp',
        name: 'Cameron Grimes',
        media: '73',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Female',
        image: './Images/RosterWwe2k24/candiceLeRae.webp',
        name: 'Candice LeRae',
        media: '67',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Global Superstars Pack',
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/carlito.webp',
        name: 'Carlito',
        media: '80',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Female',
        image: './Images/RosterWwe2k24/carmella.webp',
        name: 'Carmella',
        media: '74',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/carmeloHayes.webp',
        name: 'Carmelo Hayes',
        media: '81',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'High Flyer',
        gender: 'Male',
        image: './Images/RosterWwe2k24/cedricAlexander.webp',
        name: 'Cedric Alexander',
        media: '69',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/chadGable.webp',
        name: 'Chad Gable',
        media: '80',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/chadGable16.webp',
        name: 'Chad Gable 2016',
        media: '80',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Male',
        image: './Images/RosterWwe2k24/channingStacksLorenzo.webp',
        name: 'Channing "Stacks" Lorenzo',
        media: '69',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Female',
        image: './Images/RosterWwe2k24/charlotteFlair.webp',
        name: 'Charlotte Flair',
        media: '92',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Female',
        image: './Images/RosterWwe2k24/charlotteFlair19.webp',
        name: 'Charlotte Flair 2019',
        media: '93',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: '40 Years of WrestleMania Edition',
        cardPerson: false,
        category: 'Technician',
        gender: 'Female',
        image: './Images/RosterWwe2k24/charlotteFlair17.webp',
        name: 'Charlotte Flair 2017',
        media: '87',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Female',
        image: './Images/RosterWwe2k24/chelseaGreen.webp',
        name: 'Chelsea Green',
        media: '75',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Female',
        image: './Images/RosterWwe2k24/chyna.webp',
        name: 'Chyna',
        media: '88',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'ECW Punk Pack',
        cardPerson: false,
        category: 'Striker',
        gender: 'Male',
        image: './Images/RosterWwe2k24/cmPunk.webp',
        name: 'CM Punk',
        media: '90',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        category: 'Striker',
        gender: 'Male',
        image: './Images/RosterWwe2k24/cmPunkPiper.webp',
        name: 'CM Punk (Piper)',
        media: '90',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        category: 'Striker',
        gender: 'Male',
        image: './Images/RosterWwe2k24/cmPunkSes.webp',
        name: 'CM Punk (S.E.S.)',
        media: '90',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        category: 'Striker',
        gender: 'Male',
        image: './Images/RosterWwe2k24/cmPunk10.webp',
        name: 'CM Punk 2010',
        media: '98',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        category: 'Striker',
        gender: 'Male',
        image: './Images/RosterWwe2k24/cmPunkMasked.webp',
        name: 'CM Punk 2010 (Masked)',
        media: '90',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/codyRhodes.webp',
        name: 'Cody Rhodes',
        media: '93',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Nightmare Family Pack',
        cardPerson: true,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/codyRhodesElite.webp',
        name: 'Cody Rhodes "Élite"',
        media: '91',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Female',
        image: './Images/RosterWwe2k24/coraJade.webp',
        name: 'Cora Jade',
        media: '74',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'High Flyer',
        gender: 'Male',
        image: './Images/RosterWwe2k24/cruzDelToro.webp',
        name: 'Cruz Del Toro',
        media: '69',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/curtHennig.webp',
        name: 'Curt Hennig (Wolfpac)',
        media: '84',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'ECW Punk Pack',
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/d VonDudley.webp',
        name: 'D-Von Dudley',
        media: '84',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Female',
        image: './Images/RosterWwe2k24/dakotaKai.webp',
        name: 'Dakota Kai',
        media: '78',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Striker',
        gender: 'Male',
        image: './Images/RosterWwe2k24/damianPriest.webp',
        name: 'Damian Priest',
        media: '86',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/damonKemp.webp',
        name: 'Damon Kemp',
        media: '68',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Pat Mcafee Pack',
        cardPerson: false,
        category: 'High Flyer',
        gender: 'Male',
        image: './Images/RosterWwe2k24/dariusButler.webp',
        name: 'Darius Butler',
        media: '78',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: 'WCW Pack',
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/ddp.webp',
        name: 'DDP',
        media: '88',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/dexterLumis.webp',
        name: 'Dexter Lumis',
        media: '66',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/diesel.webp',
        name: 'Diesel',
        category: 'Powerhouse',
        media: '87',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/dijak.webp',
        name: 'Dijak',
        category: 'Powerhouse',
        media: '77',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/dirtyDominikMysterio.webp',
        name: 'Dirty Dominik Mysterio',
        category: 'Striker',
        media: '83',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/dirtyDominikMysterioMasked.webp',
        name: 'Dirty Dominik Mysterio (Masked)',
        category: 'Striker',
        media: '83',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/doinkTheClown.webp',
        name: 'Doink The Clown',
        category: 'Technician',
        media: '74',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Global Superstars Pack',
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/dragonLee.webp',
        name: 'Dragon Lee',
        category: 'High Flyer',
        media: '77',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/drewGulak.webp',
        name: 'Drew Gulak',
        category: 'Technician',
        media: '70',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/drewMcIntyre.webp',
        name: 'Drew McIntyre',
        category: 'Powerhouse',
        media: '89',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/dudeLove.webp',
        name: 'Dude Love',
        category: 'Powerhouse',
        media: '81',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/dukeHudson.webp',
        name: 'Duke Hudson',
        category: 'Powerhouse',
        media: '71',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Nightmare Family Pack',
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/dustyRhodes.webp',
        name: 'Dusty Rhodes',
        category: 'Technician',
        media: '91',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/eddieGuerrero.webp',
        name: 'Eddie Guerrero',
        category: 'Technician',
        media: '90',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/eddieGuerrero97.webp',
        name: 'Eddie Guerrero 1997',
        category: 'High Flyer',
        media: '76',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/eltonPrince.webp',
        name: 'Elton Prince',
        category: 'Technician',
        media: '76',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/ericBischoff.webp',
        name: 'Eric Bischoff',
        category: 'Striker',
        media: '58',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/erik.webp',
        name: 'Erik',
        category: 'Striker',
        media: '78',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/eveTorres.webp',
        name: 'Eve Torres',
        category: 'Striker',
        media: '85',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/faarooq.webp',
        name: 'Faarooq',
        category: 'Powerhouse',
        media: '85',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/fallonHenley.webp',
        name: 'Fallon Henley',
        category: 'Striker',
        media: '66',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/theFiendBrayWyatt.webp',
        name: 'The Fiend Bray Wyatt',
        category: 'Powerhouse',
        media: '92',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Bray Wyatt Edition Pack',
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/theFiendBrayWyatt23.webp',
        name: 'The Fiend Bray Wyatt 2023',
        category: 'Powerhouse',
        media: '94',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/finnBalor.webp',
        name: 'Finn Bálor',
        category: 'Striker',
        media: '87',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/georgeTheAnimalSteele.webp',
        name: 'George "The Animal" Steele',
        category: 'Powerhouse',
        media: '79',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/gigiDolin.webp',
        name: 'Gigi Dolin',
        category: 'Striker',
        media: '74',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/giovanniVinci.webp',
        name: 'Giovanni Vinci',
        category: 'Technician',
        media: '72',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/graysonWaller.webp',
        name: 'Grayson Waller',
        category: 'Striker',
        media: '74',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'WCW Pack',
        cardPerson: false,
        category: 'Striker',
        gender: 'Male',
        image: './Images/RosterWwe2k24/theGreatMuta.webp',
        name: 'The Great Muta',
        media: '86',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/gunther.webp',
        name: 'Gunther',
        category: 'Powerhouse',
        media: '90',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/harleyRace.webp',
        name: 'Harley Race',
        category: 'Technician',
        media: '84',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/hollywoodHogan.webp',
        name: 'Hollywood Hogan',
        category: 'Powerhouse',
        media: '92',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/hollywoodHoganWolfpac.webp',
        name: 'Hollywood Hogan (Wolfpac)',
        category: 'Powerhouse',
        media: '98',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Pat Mcafee Pack',
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/honkyTonkMan.webp',
        name: 'Honky Tonk Man',
        category: 'Technician',
        media: '81',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/hulkHogan.webp',
        name: 'Hulk Hogan',
        category: 'Powerhouse',
        media: '94',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/hulkHoganElite.webp',
        name: 'Hulk Hogan "Élite"',
        category: 'Powerhouse',
        media: '94',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/hulkHoganIchiban.webp',
        name: 'Hulk Hogan "Ichiban"',
        category: 'Powerhouse',
        media: '94',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/hulkHogan02.webp',
        name: 'Hulk Hogan 2002',
        category: 'Powerhouse',
        media: '89',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/humbertoCarrillo.webp',
        name: 'Humberto Carrillo',
        category: 'High Flyer',
        media: '65',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/theHurricane.webp',
        name: 'The Hurricane',
        category: 'Technician',
        media: '75',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/iljaDragunov.webp',
        name: 'Ilja Dragunov',
        category: 'Striker',
        media: '81',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/indiHartwell.webp',
        name: 'Indi Hartwell',
        category: 'Striker',
        media: '63',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'WCW Pack',
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/theIronSheik.webp',
        name: 'The Iron Sheik',
        media: '85',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/islaDawn.webp',
        name: 'Isla Dawn',
        category: 'Striker',
        media: '74',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/ivar.webp',
        name: 'Ivar',
        category: 'Powerhouse',
        media: '79',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        image: './Images/RosterWwe2k24/ivyNile.webp',
        gender: 'Female',
        name: 'Ivy Nile',
        category: 'Powerhouse',
        media: '73',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/iyoSky.webp',
        name: 'Iyo Sky',
        category: 'High Flyer',
        media: '88',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/jacyJayne.webp',
        name: 'Jacy Jayne',
        category: 'Striker',
        media: '73',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Global Superstars Pack',
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/jadeCargill.webp',
        name: 'Jade Cargill',
        category: 'Powerhouse',
        media: '85',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/jakeTheSnakeRoberts.webp',
        name: 'Jake "The Snake" Roberts',
        category: 'Striker',
        media: '85',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/jbl.webp',
        name: 'JBL',
        category: 'Powerhouse',
        media: '89',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/jdMcDonagh.webp',
        name: 'JD McDonagh',
        category: 'Technician',
        media: '71',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/jeanPaulLevesque.webp',
        name: 'Jean-Paul Levesque',
        category: 'Powerhouse',
        media: '87',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/jerryTheKingLawler.webp',
        name: 'Jerry "The King" Lawler',
        category: 'Striker',
        media: '86',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/jeyUso.webp',
        name: 'Jey Uso',
        category: 'Striker',
        media: '90',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/jimTheAnvilNeidhart.webp',
        name: 'Jim "The Anvil" Neidhart',
        category: 'Powerhouse',
        media: '80',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/jimmyUso.webp',
        name: 'Jimmy Uso',
        category: 'Striker',
        media: '84',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/jinderMahal.webp',
        name: 'Jinder Mahal',
        category: 'Striker',
        media: '74',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/joaquinWilde.webp',
        name: 'Joaquin Wilde',
        category: 'High Flyer',
        media: '68',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/joeCoffey.webp',
        name: 'Joe Coffey',
        category: 'Technician',
        media: '76',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/joeGacy.webp',
        name: 'Joe Gacy',
        category: 'Striker',
        media: '73',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/johnCena.webp',
        name: 'John Cena',
        category: 'Powerhouse',
        media: '94',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/johnCenaElite.webp',
        name: 'John Cena "Élite"',
        category: 'Powerhouse',
        media: '94',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/johnCenaThePrototype.webp',
        name: 'John Cena (The Prototype)',
        category: 'Powerhouse',
        media: '92',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/johnCena02.webp',
        name: 'John Cena 2002',
        category: 'Powerhouse',
        media: '75',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/johnCena20.webp',
        name: 'John Cena 2020',
        category: 'Powerhouse',
        media: '89',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/johnCena20Doc.webp',
        name: 'John Cena 2020 (DOC)',
        category: 'Powerhouse',
        media: '86',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/johnCena20Nwo.webp',
        name: 'John Cena 2020 (nWo)',
        category: 'Powerhouse',
        media: '91',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/johnCena20Snme.webp',
        name: 'John Cena 2020 (SNME)',
        category: 'Powerhouse',
        media: '85',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/johnCena20Wm30.webp',
        name: 'John Cena 2020 (WM30)',
        category: 'Powerhouse',
        media: '89',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/johnnyGargano.webp',
        name: 'Johnny Gargano',
        category: 'Technician',
        media: '74',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/joshBriggs.webp',
        name: 'Josh Briggs',
        category: 'Powerhouse',
        media: '69',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/juanCena.webp',
        name: 'Juan Cena',
        category: 'Powerhouse',
        media: '96',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/juliusCreed.webp',
        name: 'Julius Creed',
        category: 'Powerhouse',
        media: '79',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Global Superstars Pack',
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/kairiSane.webp',
        name: 'Kairi Sane',
        category: 'Striker',
        media: '78',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/kane.webp',
        name: 'Kane',
        category: 'Powerhouse',
        media: '79',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/kane08.webp',
        name: 'Kane 2008',
        category: 'Powerhouse',
        media: '85',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/karlAnderson.webp',
        name: 'Karl Anderson',
        category: 'Striker',
        media: '72',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/karrionKross.webp',
        name: 'Karrion Kross',
        category: 'Striker',
        media: '75',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/katanaChance.webp',
        name: 'Katana Chance',
        category: 'High Flyer',
        media: '74',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/kaydenCarter.webp',
        name: 'Kayden Carter',
        category: 'Technician',
        media: '74',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/kenShamrock.webp',
        name: 'Ken Shamrock',
        category: 'Striker',
        media: '86',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/kevinNash.webp',
        name: 'Kevin Nash',
        category: 'Powerhouse',
        media: '88',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/kevinOwens.webp',
        name: 'Kevin Owens',
        category: 'Striker',
        media: '86',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/kevinOwensStoneCold.webp',
        name: 'Kevin Owens (Stone Cold)',
        category: 'Striker',
        media: '86',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        category: 'Striker',
        gender: 'Male',
        image: './Images/RosterWwe2k24/kingBookerT.webp',
        name: 'King Booker T',
        media: '92',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/kitWilson.webp',
        name: 'Kit Wilson',
        category: 'Technician',
        media: '76',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/kofiKingston.webp',
        name: 'Kofi Kingston',
        category: 'Striker',
        media: '80',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/kurtAngle.webp',
        name: 'Kurt Angle',
        category: 'Technician',
        media: '89',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/laKnight.webp',
        name: 'LA Knight',
        category: 'Striker',
        media: '88',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'WCW Pack',
        cardPerson: false,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/lexLuger.webp',
        name: 'Lex Luger',
        media: '87',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        category: 'Powerhouse',
        gender: 'Male',
        image: './Images/RosterWwe2k24/lexLugerWolfpac.webp',
        name: 'Lex Luger (Wolfpac)',
        media: '87',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/lita.webp',
        name: 'Lita',
        category: 'High Flyer',
        media: '86',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/livMorgan.webp',
        name: 'Liv Morgan',
        category: 'Striker',
        media: '85',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/loganPaul.webp',
        name: 'Logan Paul',
        category: 'Striker',
        media: '90',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/ludwigKaiser.webp',
        name: 'Ludwig Kaiser',
        category: 'Technician',
        media: '73',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/lukeGallows.webp',
        name: 'Luke Gallows',
        category: 'Powerhouse',
        media: '73',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Global Superstars Pack',
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/lyraValkyria.webp',
        name: 'Lyra Valkyria',
        category: 'Striker',
        media: '80',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: '40 Years of WrestleMania Edition',
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/machoKingRandySavage.webp',
        name: '"Macho King" Randy Savage',
        category: 'High Flyer',
        media: '88',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/machoManRandySavage.webp',
        name: '"Macho Man" Randy Savage',
        category: 'High Flyer',
        media: '89',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/machoManRandySavageWolfpac.webp',
        name: '"Macho Man" Randy Savage (Wolfpac)',
        category: 'High Flyer',
        media: '89',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/mankind.webp',
        name: 'Mankind',
        category: 'Powerhouse',
        media: '86',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/markCoffey.webp',
        name: 'Mark Coffey',
        category: 'Technician',
        media: '74',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/maryse.webp',
        name: 'Maryse',
        category: 'Striker',
        media: '79',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/maxxineDupri.webp',
        name: 'Maxxine Dupri',
        category: 'Striker',
        media: '64',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Global Superstars Pack',
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/michelleMcCool.webp',
        name: 'Michelle McCool',
        category: 'Technician',
        media: '85',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/michin.webp',
        name: 'Michin',
        category: 'Striker',
        media: '68',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Female',
        image: './Images/RosterWwe2k24/michin64Bit.webp',
        name: 'Michin (64 Bit)',
        category: 'Striker',
        media: '75',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/mightyMolly.webp',
        name: 'Mighty Molly',
        category: 'Technician',
        media: '75',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/theMiz.webp',
        name: 'The Miz',
        category: 'Striker',
        media: '81',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/mollyHolly.webp',
        name: 'Molly Holly',
        category: 'Technician',
        media: '83',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/montezFord.webp',
        name: 'Montez Ford',
        category: 'High Flyer',
        media: '76',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Post Malone & Friends Pack',
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/mosh.webp',
        name: 'Mosh',
        category: 'Striker',
        media: '76',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'WCW Pack',
        cardPerson: false,
        category: 'Technician',
        gender: 'Male',
        image: './Images/RosterWwe2k24/mrPerfect.webp',
        name: 'Mr. Perfect',
        media: '84',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/muhammadAli.webp',
        name: 'Muhammad Ali',
        category: 'Striker',
        media: '91',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/mvp.webp',
        name: 'MVP',
        category: 'Striker',
        media: '68',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/natalya.webp',
        name: 'Natalya',
        category: 'Technician',
        media: '81',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/nathanFrazer.webp',
        name: 'Nathan Frazer',
        category: 'High Flyer',
        media: '75',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Global Superstars Pack',
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/niaJax.webp',
        name: 'Nia Jax',
        category: 'Powerhouse',
        media: '86',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/nikkiCross.webp',
        name: 'Nikki Cross',
        category: 'Striker',
        media: '62',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/nikkitaLyons.webp',
        name: 'Nikkita Lyons',
        category: 'Striker',
        media: '73',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/noamDar.webp',
        name: 'Noam Dar',
        category: 'Striker',
        media: '76',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/omos.webp',
        name: 'Omos',
        category: 'Powerhouse',
        media: '76',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/otis.webp',
        name: 'Otis',
        category: 'Powerhouse',
        media: '74',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Pat Mcafee Pack',
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/patMcAfee.webp',
        name: 'Pat McAfee',
        category: 'Striker',
        media: '80',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/piperNiven.webp',
        name: 'Piper Niven',
        category: 'Powerhouse',
        media: '79',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Post Malone & Friends Pack',
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/postMalone.webp',
        name: 'Post Malone',
        category: 'Technician',
        media: '69',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/r-truth.webp',
        name: 'R-Truth',
        category: 'Striker',
        media: '67',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/randyOrton.webp',
        name: 'Randy Orton',
        category: 'Technician',
        media: '91',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/randyOrton09.webp',
        name: 'Randy Orton 2009',
        category: 'Technician',
        media: '93',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/randyOrton02.webp',
        name: 'Randy Orton 2002',
        category: 'Technician',
        media: '68',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/randyOrton15.webp',
        name: 'Randy Orton 2015',
        category: 'Technician',
        media: '90',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/raquelRodriguez.webp',
        name: 'Raquel Rodriguez',
        category: 'Powerhouse',
        media: '86',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Female',
        image: './Images/RosterWwe2k24/raquelRodriguezDm.webp',
        name: 'Raquel Rodriguez (DM)',
        category: 'Powerhouse',
        media: '84',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/ravishingRickRude.webp',
        name: '"Ravishing" Rick Rude',
        category: 'Technician',
        media: '84',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/razorRamon.webp',
        name: 'Razor Ramon',
        category: 'Powerhouse',
        media: '87',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/reyMysterio.webp',
        name: 'Rey Mysterio',
        category: 'High Flyer',
        media: '88',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/reyMysterioJr.webp',
        name: 'Rey Mysterio Jr.',
        category: 'High Flyer',
        media: '74',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: '40 Years of WrestleMania Edition',
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/reyMysterio06.webp',
        name: 'Rey Mysterio 2006',
        category: 'High Flyer',
        media: '87',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/rheaRipley.webp',
        name: 'Rhea Ripley',
        category: 'Powerhouse',
        media: '96',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Female',
        image: './Images/RosterWwe2k24/rheaRipley23CrownJewel.webp',
        name: 'Rhea Ripley 2023 (CrownJewel)',
        category: 'Powerhouse',
        media: '98',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Female',
        image: './Images/RosterWwe2k24/rheaRipleyhhh.webp',
        name: 'Rhea Ripley (HHH)',
        category: 'Powerhouse',
        media: '94',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Deluxe Edition',
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/rheaRipley17.webp',
        name: 'Rhea Ripley 2017',
        category: 'Powerhouse',
        media: '72',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: '40 Years of WrestleMania Edition',
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/rheaRipley20.webp',
        name: 'Rhea Ripley 2020',
        category: 'Powerhouse',
        media: '80',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/rickSteiner.webp',
        name: 'Rick Steiner',
        category: 'Technician',
        media: '83',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/rickyTheDragonSteamboat.webp',
        name: 'Ricky "The Dragon" Steamboat',
        category: 'High Flyer',
        media: '88',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/ricochet.webp',
        name: 'Ricochet',
        category: 'High Flyer',
        media: '81',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/ridgeHolland.webp',
        name: 'Ridge Holland',
        category: 'Powerhouse',
        media: '76',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/rikishi.webp',
        name: 'Rikishi',
        category: 'Powerhouse',
        media: '79',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/robVanDam.webp',
        name: 'Rob Van Dam',
        category: 'High Flyer',
        media: '90',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/robertRoode.webp',
        name: 'Robert Roode',
        category: 'Technician',
        media: '67',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/theRock.webp',
        name: 'The Rock',
        category: 'Powerhouse',
        media: '94',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/theRockElite.webp',
        name: 'The Rock "Élite"',
        category: 'Powerhouse',
        media: '85',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/theRock01.webp',
        name: 'The Rock 2001',
        category: 'Striker',
        media: '96',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/theRock04.webp',
        name: 'The Rock 2004',
        category: 'Striker',
        media: '86',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/romanReigns.webp',
        name: 'Roman Reigns',
        category: 'Powerhouse',
        media: '97',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/romanReigns64Bit.webp',
        name: 'Roman Reigns (64 Bit)',
        category: 'Powerhouse',
        media: '76',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/romanReigns15.webp',
        name: 'Roman Reigns 2015',
        category: 'Powerhouse',
        media: '90',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/romanReigns24.webp',
        name: 'Roman Reigns 2024',
        category: 'Powerhouse',
        media: '85',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/rondaRousey.webp',
        name: 'Ronda Rousey',
        category: 'Striker',
        media: '91',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/rowdyRoddyPiper.webp',
        name: '"Rowdy" Roddy Piper',
        category: 'Striker',
        media: '84',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/roxannePerez.webp',
        name: 'Roxanne Perez',
        category: 'Striker',
        media: '78',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/samiZayn.webp',
        name: 'Sami Zayn',
        category: 'Technician',
        media: '87',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'ECW Punk Pack',
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/theSandman.webp',
        name: 'The Sandman',
        category: 'Powerhouse',
        media: '86',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/sanga.webp',
        name: 'Sanga',
        category: 'Powerhouse',
        media: '71',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/santosEscobar.webp',
        name: 'Santos Escobar',
        category: 'Technician',
        media: '78',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/scarlett.webp',
        name: 'Scarlett',
        category: 'Striker',
        media: '69',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/scottHall.webp',
        name: 'Scott Hall',
        category: 'Powerhouse',
        media: '87',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/scottSteiner.webp',
        name: 'Scott Steiner',
        category: 'Technician',
        media: '83',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/scrypts.webp',
        name: 'Scrypts',
        category: 'High Flyer',
        media: '61',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Post Malone & Friends Pack',
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/sensationalSherri.webp',
        name: 'Sensational Sherri',
        category: 'Striker',
        media: '80',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/sethFreakinRollins.webp',
        name: 'Seth "Freakin" Rollins',
        category: 'Technician',
        media: '93',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/sethRollins14.webp',
        name: 'Seth Rollins 2014',
        category: 'Striker',
        media: '81',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/sethRollins15.webp',
        name: 'Seth Rollins 2015',
        category: 'Striker',
        media: '89',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/shaneMcMahon.webp',
        name: 'Shane McMahon',
        category: 'Striker',
        media: '79',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/shawnMichaels.webp',
        name: 'Shawn Michaels',
        category: 'Striker',
        media: '87',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/shawnMichaels94.webp',
        name: 'Shawn Michaels 1994',
        category: 'Striker',
        media: '85',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/shawnMichaels05.webp',
        name: 'Shawn Michaels 2005',
        category: 'Striker',
        media: '89',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/shawnMichaels09.webp',
        name: 'Shawn Michaels 2009',
        category: 'Striker',
        media: '93',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/shaynaBaszler.webp',
        name: 'Shayna Baszler',
        category: 'Striker',
        media: '82',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/sheamus.webp',
        name: 'Sheamus',
        category: 'Striker',
        media: '86',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/sheamus09.webp',
        name: 'Sheamus 2009',
        category: 'Striker',
        media: '79',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/shinsukeNakamura.webp',
        name: 'Shinsuke Nakamura',
        category: 'Striker',
        media: '84',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/shotzi.webp',
        name: 'Shotzi',
        category: 'Striker',
        media: '76',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/machoManRandySavageSlimJim.webp',
        name: '"Slim Jim" Macho Man Randy Savage',
        category: 'High Flyer',
        media: '89',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/soloSikoa.webp',
        name: 'Solo Sikoa',
        category: 'Striker',
        media: '86',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/sonyaDeville.webp',
        name: 'Sonya Deville',
        category: 'Striker',
        media: '74',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/stacyKeibler.webp',
        name: 'Stacy Keibler',
        category: 'Striker',
        media: '75',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Nightmare Family Pack',
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/stardust.webp',
        name: 'Stardust',
        category: 'Technician',
        media: '74',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/stephanieMcMahon.webp',
        name: 'Stephanie McMahon',
        category: 'Striker',
        media: '75',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/stoneColdSteveAustin.webp',
        name: 'Stone Cold Steve Austin',
        category: 'Striker',
        media: '86',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/stoneColdSteveAustin97.webp',
        name: 'Stone Cold Steve Austin 1997',
        category: 'Striker',
        media: '89',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/stoneColdSteveAustin21.webp',
        name: 'Stone Cold Steve Austin 2001',
        category: 'Striker',
        media: '96',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Nightmare Family Pack',
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/superstarBillyGraham.webp',
        name: 'Superstar Billy Graham',
        category: 'Powerhouse',
        media: '92',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/syxx.webp',
        name: 'Syxx',
        category: 'Striker',
        media: '76',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/tamina.webp',
        name: 'Tamina',
        category: 'Powerhouse',
        media: '67',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/tedDiBiase.webp',
        name: 'Ted DiBiase',
        category: 'Technician',
        media: '85',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/teganNox.webp',
        name: 'Tegan Nox',
        category: 'Striker',
        media: '77',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'ECW Punk Pack',
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/terryFunk.webp',
        name: 'Terry Funk',
        category: 'Technician',
        media: '87',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/theaHail.webp',
        name: 'Thea Hail',
        category: 'Striker',
        media: '72',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/thrasher.webp',
        name: 'Thrasher',
        category: 'Striker',
        media: '76',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/tiffanyStratton.webp',
        name: 'Tiffany Stratton',
        category: 'Striker',
        media: '79',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/tommasoCiampa.webp',
        name: 'Tommaso Ciampa',
        category: 'Striker',
        media: '76',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/tonyDAngelo.webp',
        name: 'Tony D\'Angelo',
        category: 'Technician',
        media: '75',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/trickWilliams.webp',
        name: 'Trick Williams',
        category: 'Striker',
        media: '78',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/trickWilliams22.webp',
        name: 'Trick Williams 2022',
        category: 'Striker',
        media: '82',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/tripleH.webp',
        name: 'Triple H',
        category: 'Powerhouse',
        media: '91',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/tripleHKingOfRings.webp',
        name: 'Triple H (King Of Rings)',
        category: 'Powerhouse',
        media: '97',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/tripleH08.webp',
        name: 'Triple H 2008',
        category: 'Powerhouse',
        media: '91',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: '40 Years of WrestleMania Edition',
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/tripleH14.webp',
        name: 'Triple H 2014',
        category: 'Powerhouse',
        media: '89',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/trishStratus.webp',
        name: 'Trish Stratus',
        category: 'Striker',
        media: '89',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Pat Mcafee Pack',
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/tySchmit.webp',
        name: 'Ty Schmit',
        category: 'Technician',
        media: '69',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/tylerBate.webp',
        name: 'Tyler Bate',
        category: 'Technician',
        media: '76',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/tylerBreeze.webp',
        name: 'Tyler Breeze',
        category: 'Striker',
        media: '75',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/ultimateWarrior.webp',
        name: 'Ultimate Warrior',
        category: 'Powerhouse',
        media: '92',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/umaga.webp',
        name: 'Umaga',
        category: 'Powerhouse',
        media: '86',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/uncleHowdy.webp',
        name: 'Uncle Howdy',
        category: 'Powerhouse',
        media: '82',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/uncleHowdy24.webp',
        name: 'Uncle Howdy 2024',
        category: 'Powerhouse',
        media: '87',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: 'Nightmare Family Pack',
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/undashingCodyRhodes.webp',
        name: 'Undashing Cody Rhodes',
        category: 'Technician',
        media: '85',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/undertaker.webp',
        name: 'Undertaker',
        category: 'Striker',
        media: '95',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/undertaker98.webp',
        name: 'Undertaker 1998',
        category: 'Striker',
        media: '93',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/undertaker03.webp',
        name: 'Undertaker 2003',
        category: 'Striker',
        media: '92',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/undertaker09.webp',
        name: 'Undertaker 2009',
        category: 'Striker',
        media: '96',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/undertaker14.webp',
        name: 'Undertaker 2014',
        category: 'Striker',
        media: '94',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/undertaker20.webp',
        name: 'Undertaker 2020',
        category: 'Striker',
        media: '94',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/vader.webp',
        name: 'Vader',
        category: 'Powerhouse',
        media: '87',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/valhalla.webp',
        name: 'Valhalla',
        category: 'Striker',
        media: '63',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/veerMahaan.webp',
        name: 'Veer Mahaan',
        category: 'Powerhouse',
        media: '75',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/wadeBarrett.webp',
        name: 'Wade Barrett',
        category: 'Striker',
        media: '85',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/wendyChoo.webp',
        name: 'Wendy Choo',
        category: 'Striker',
        media: '72',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/wesLee.webp',
        name: 'Wes Lee',
        category: 'High Flyer',
        media: '76',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/williamRegal.webp',
        name: 'William Regal',
        category: 'Technician',
        media: '76',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/wolfgang.webp',
        name: 'Wolfgang',
        category: 'Powerhouse',
        media: '73',
        weight: 'Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/x-pac.webp',
        name: 'X-Pac',
        category: 'Striker',
        media: '78',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/xavierWoods.webp',
        name: 'Xavier Woods',
        category: 'Striker',
        media: '78',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/xavierWoods64Bit.webp',
        name: 'Xavier Woods (64 Bit)',
        category: 'Striker',
        media: '80',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/xiaLi.webp',
        name: 'Xia Li',
        category: 'Striker',
        media: '73',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Male',
        image: './Images/RosterWwe2k24/yokozuna.webp',
        name: 'Yokozuna',
        category: 'Powerhouse',
        media: '90',
        weight: 'Super Heavyweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/zelinaVega.webp',
        name: 'Zelina Vega',
        category: 'High Flyer',
        media: '74',
        weight: 'Cruserweight',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: true,
        gender: 'Male',
        image: './Images/RosterWwe2k24/zero.webp',
        name: 'Zero',
        category: 'Technician',
        media: '78',
        weight: '',
        tags: [],
        available: true
    },
    {
        dlc: null,
        cardPerson: false,
        gender: 'Female',
        image: './Images/RosterWwe2k24/zoeyStark.webp',
        name: 'Zoey Stark',
        category: 'Striker',
        media: '78',
        weight: 'Light Heavyweight',
        tags: [],
        available: true
    },
]

export { RosterWwe2k24 }